---
title: "BMI 510: Homework #3"
author: "Alireza Rafiei"
date: "02/03/2023"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r }
# Required libraries
library(ggplot2)
library(tidyr)
```

# Q1

```{r }

plot_frequency_function = function(X, P){
  df = data.frame(X = X, P = P)
  ggplot(df, aes(x = X, y = P)) +
  geom_bar(stat = "identity") +
  xlab("X") +
  ylab("Density")
}

plot_cumulative_function = function(X, P){
  df = data.frame(X = X, P = P)
    
  ggplot(df, aes(x = X, y = cumsum(P))) +
  geom_step(size = 1.5)+
  xlab("X") +
  ylab("Cumulative Density")+
  ylim(0,1)
}

plot_frequency_function(X = 0:3,P = c(0.25,0.125,0.125,0.5))
plot_cumulative_function(X = 0:3,P = c(0.25,0.125,0.125,0.5))
```


# Q2

```{r }
frequency_function = function(X, CF){

  freq_func = diff(CF)
  print(freq_func)
  df = data.frame(X = X, y = c(0,freq_func))
  ggplot(df, aes(x = X, y = y)) +
  geom_bar(stat = "identity") +
  xlab("X") +
  ylab("Count")
}

frequency_function(X = 0:5, CF = c(0,20,60,140,160,200))
```


# Q3

```{r }
print('Examination #1: Are these numbers the same?')
pi_user = 3.14159
print(identical(pi, pi_user))

print('Examination #2: Are these numbers the same?')
print(all.equal(pi, pi_user))

print('Examination #3: Are these numbers the same?')
print(all.equal(pi, pi_user, 1e-5))

```


# Q4

```{r }
a = 3    # Chose a scalar number
x = 1:12

match(a,x)
min(which(x == a))

print("deos match(a,x) equivalent to min(which(x == a))?\n")
match(a,x) == min(which(x == a))

print("x %in% 4 is")
x %in% 4 

print("x %in% c(5,10) is")
x %in% c(5,10)
```


# Q5

```{r }
BoxMuller = function(n, verbose){
  
  samples <- matrix(ncol=2,nrow=n)
  for (i in 1:n){
    u1 = runif(1)
    u2 = runif(1)
    R = sqrt(-2*log(1-u1))
    Theta = 2*pi*u2
    x = R*cos(Theta)
    y = R*sin(Theta)
    samples[i,1] = x
    samples[i,2] = y
 }
 norm = rnorm(n)
 x = samples[,1]
 y = samples[,2]
 
 if (verbose == 0){
  df = data.frame(x = x,y = y, norm =norm)
  return(df)
 }
 
  if (verbose == 1){
    values = c(samples[,1],samples[,2])
    return(values)
  }
 
  if (verbose == 2){
    return(norm)
  }
 
}

BoxMuller(n = 500, verbose = 0)

mean(BoxMuller(n = 500, verbose = 1))
var(BoxMuller(n = 500, verbose = 1))
```


# Q6

```{r }
# Don't forget to run BoxMuller() first!
ggplot(, aes(BoxMuller(n = 10000, verbose = 1))) +
geom_density(size=1) +
xlab("x") +
ylab("f(x)") +
ggtitle("Output of your BoxMuller() function")

ggplot(, aes(BoxMuller(n = 10000, verbose = 2))) +
geom_density(size=1) +
xlab("x") +
ylab("f(x)") + 
ggtitle("Output of rnorm() function")


#############################
##       Extra point       ##
#############################

data = pivot_longer(BoxMuller(n = 10000, verbose = 0) ,cols = c("x","y", "norm"))
data[data == 'x' | data == 'y'] = 'BoxMuller'
data[data == 'norm'] = 'rnorm'
ggplot(data, aes(x=value, color=name, fill=name)) + 
geom_density(size=1, alpha = .1) +
labs(x="x", y="f(x)") 

```


# Q7

```{r }
# Don't forget to run BoxMuller() first!
ggplot(, aes(BoxMuller(n = 10000, verbose = 1))) +
stat_ecdf(geom = "step",size = 1.5)+
xlab("X") +
ylab("Cumulative Density")

```


# Q8

```{r }
# Don't forget to run BoxMuller() first!
Unif12 = function(n = 1){
  
  unif12s = c()
  for (i in 1:n){
    vars = runif(12, min = -0.5, max = 0.5)
    unif12s = c(unif12s, sum(vars))
    
  }
  
  return(unif12s)
}

Unif12()


n = 10000
BoxMuller_samples = BoxMuller(n, verbose = 1)
rnorm_samples = rnorm(n)
Unif12_samples = Unif12(n)

BoxMuller_dataframe = data.frame(BoxMuller_samples)
rnorm_dataframe = data.frame(rnorm_samples)
Unif12_dataframe = data.frame(Unif12_samples)

ggplot(BoxMuller_dataframe,aes(x = BoxMuller_samples)) +
  geom_density(size = 1.5)

ggplot(rnorm_dataframe, aes(x = rnorm_samples)) +
  geom_density(size = 1.5)

ggplot(Unif12_dataframe, aes(x = Unif12_samples)) +
  geom_density(size = 1.5)


Integrated_dataframe = data.frame(BoxMuller_dataframe, rnorm_dataframe, Unif12_dataframe)

Integrated_dataframe %>%
  pivot_longer(cols = everything()) %>%
  ggplot(aes(x = value, group = name, color = name, fill=name)) +
  geom_density(size=1, alpha = .1) +
  labs(x="x", y="f(x)") 
```


# Q9

```{r }
# There are two ways to generate the required data.
# First, using rnorm to the power of two
# Second, using rchisq(n,df=1) function

chi_squared_distribution_hist = function(n, verbose = 0){
  
    if (verbose == 0){
      data = rnorm(n)
      data_2 = data^2
    }
  
    if (verbose == 1){
      data_2 = rchisq(n,df=1)
    }    

    df = data.frame(data_2)
    ggplot(df, aes(x = data_2)) +
    geom_histogram(color="black", fill="white", binwidth=0.2) +
    ggtitle('Histogram of Z^2')
}

chi_squared_distribution_dens = function(n, verbose = 0){
    
  if (verbose == 0){
      data = rnorm(n)
      data_2 = data^2
    }
  
    if (verbose == 1){
      data_2 = rchisq(n,df=1)
    }   

    df = data.frame(data_2)
    ggplot() +
    geom_density(data=df, aes(x = data_2), size =1) +
    labs(x="x", y="f(x)") +
    ggtitle('Density of Z^2')
    
}


chi_squared_distribution_dens_adjust = function(n, adjust, verbose = 0){
    
  if (verbose == 0){
      data = rnorm(n)
      data_2 = data^2
    }
  
    if (verbose == 1){
      data_2 = rchisq(n,df=1)
    }   

    df = data.frame(data_2)
    ggplot() +
    geom_density(data=df, aes(x = data_2), size =1, adjust = adjust) +
    labs(x="x", y="f(x)") +
    ggtitle('Density with adjust of Z^2')
    
}

chi_squared_distribution_hist(500)
chi_squared_distribution_dens(500)
# We don't have any negative value, and the density is high near zero.
chi_squared_distribution_dens_adjust(500, adjust = 1/10)
# adjust command makes it possible to adjust the bandwidth while still using the a bandwidth estimator.
```


# Q10

```{r }
ecdf_pnorm_comparison = function(n){
  data = rnorm(n)
  
  ecdf_func= ecdf(data)
  ecdf_data = ecdf_func(data)
  pnorm_data = pnorm(data)
  
  pnorm_dataframe = data.frame(pnorm_data)
  ecdf_dataframe = data.frame(ecdf_data)
  
  ggplot(ecdf_dataframe, aes(ecdf_data)) +
  geom_density()

  ggplot(pnorm_dataframe, aes(pnorm_data)) +
  geom_density()

integrated_dataframe = data.frame(ecdf_data, pnorm_data)

integrated_dataframe %>% pivot_longer(cols =everything()) %>%
  ggplot(aes(x = value, group = name, color = name)) +
  geom_density(size =1)
  
}

ecdf_pnorm_comparison(200)
ecdf_pnorm_comparison(10000)

```

